/* 여행지 기본 데이터. 개인 날짜·사진·메모는 사용자가 직접 기록합니다. */
window.TRAVEL_DATA = {
  visited: [
    {id:'london',name:'런던',en:'London',country:'영국',region:'europe',lat:51.5074,lon:-0.1278,art:'london',description:'고전과 일상이 나란히 걷는 도시',tags:['도시 산책','예술과 문화'],spots:['템스강','웨스트민스터','사우스뱅크'],intro:'템스강을 따라 이어지는 산책길과 박물관, 오래된 서점이 어우러지는 도시입니다. 런던에서 기억하고 싶은 순간을 남겨보세요.'},
    {id:'paris',name:'파리',en:'Paris',country:'프랑스',region:'europe',lat:48.8566,lon:2.3522,art:'paris',description:'골목마다 한 장의 영화 같은 풍경',tags:['미술관','카페와 골목'],spots:['센강','에펠탑','몽마르트르'],intro:'센강의 다리와 작은 카페, 미술관으로 이어지는 하루. 명소 사이에 숨은 나만의 파리를 기록할 수 있는 페이지입니다.'},
    {id:'annecy',name:'안시',en:'Annecy',country:'프랑스',region:'europe',lat:45.8992,lon:6.1294,art:'lake',description:'맑은 호수와 알프스 사이의 작은 쉼표',tags:['호수','오래된 마을'],spots:['안시 호수','구시가지','팔레 드 릴'],intro:'운하가 지나는 구시가지와 알프스 아래 펼쳐지는 호수. 천천히 걸으며 만나는 작은 풍경들을 모아보세요.'},
    {id:'south-france',name:'남프랑스',en:'South of France',country:'프랑스',region:'europe',lat:43.7102,lon:7.2620,art:'coast',description:'햇빛과 바다, 느리게 흐르는 오후',tags:['지중해','햇살 가득'],spots:['니스','에즈','프로방스'],intro:'지중해 연안과 프로방스의 마을을 품은 넓은 지역입니다. 지도는 대표 도시 니스를 표시하며, 실제 다녀온 도시는 메모에 추가해 주세요.'},
    {id:'italy',name:'이탈리아',en:'Italy',country:'이탈리아',region:'europe',lat:41.9028,lon:12.4964,art:'italy',description:'시간이 쌓인 거리, 마음에 남은 식탁',tags:['건축','미식'],spots:['로마','피렌체','베네치아'],intro:'역사적인 건축과 지역마다 다른 음식이 여행의 즐거움을 더합니다. 지도는 로마를 대표 지점으로 사용합니다.'},
    {id:'switzerland',name:'스위스',en:'Switzerland',country:'스위스',region:'europe',lat:46.6863,lon:7.8632,art:'alps',description:'기차 창밖으로 펼쳐지는 초록빛 알프스',tags:['알프스','기차 여행'],spots:['인터라켄','루체른','체르마트'],intro:'산과 호수, 마을을 잇는 풍경이 인상적인 여행지입니다. 지도는 인터라켄을 대표 지점으로 표시합니다.'},
    {id:'austria',name:'오스트리아',en:'Austria',country:'오스트리아',region:'europe',lat:48.2082,lon:16.3738,art:'lake',description:'음악이 흐르는 도시와 호숫가 마을',tags:['클래식','호수와 산'],spots:['빈','잘츠부르크','할슈타트'],intro:'도시의 음악과 건축, 알프스 호숫가의 풍경을 함께 떠올리게 합니다. 지도는 빈을 대표 지점으로 사용합니다.'},
    {id:'croatia',name:'크로아티아',en:'Croatia',country:'크로아티아',region:'europe',lat:42.6507,lon:18.0944,art:'coast',description:'붉은 지붕 너머 반짝이는 아드리아해',tags:['성곽 도시','바다'],spots:['두브로브니크','스플리트','플리트비체'],intro:'해안의 성곽 도시와 내륙의 호수 풍경이 만나는 곳입니다. 지도는 두브로브니크를 대표 지점으로 표시합니다.'},
    {id:'china',name:'중국',en:'China',country:'중국',region:'asia',lat:39.9042,lon:116.4074,art:'asia',description:'다채로운 풍경 속, 오래된 시간의 흔적',tags:['역사','문화'],spots:['베이징','상하이','시안'],intro:'넓은 땅만큼 서로 다른 문화와 풍경이 펼쳐집니다. 지도는 베이징을 대표 지점으로 사용하며, 방문 도시는 메모에 기록해 주세요.'},
    {id:'thailand',name:'태국',en:'Thailand',country:'태국',region:'asia',lat:13.7563,lon:100.5018,art:'tropical',description:'활기찬 시장과 여유로운 열대의 하루',tags:['미식','휴식'],spots:['방콕','치앙마이','푸껫'],intro:'도시와 북부의 마을, 남쪽의 바다까지 여행 분위기가 다양합니다. 지도는 방콕을 대표 지점으로 표시합니다.'},
    {id:'japan',name:'일본',en:'Japan',country:'일본',region:'asia',lat:35.6762,lon:139.6503,art:'japan',description:'작은 골목에서 발견한 계절의 표정',tags:['골목 산책','계절 여행'],spots:['도쿄','교토','오사카'],intro:'대도시의 거리와 조용한 정원, 지역의 작은 가게들을 돌아볼 수 있습니다. 지도는 도쿄를 대표 지점으로 사용합니다.'},
    {id:'taiwan',name:'대만',en:'Taiwan',country:'대만',region:'asia',lat:25.0330,lon:121.5654,art:'asia',description:'따뜻한 차 한 잔과 밤의 골목 여행',tags:['야시장','차 문화'],spots:['타이베이','지우펀','타이난'],intro:'골목의 먹거리와 차 문화, 산과 해안의 풍경이 가까이 있습니다. 지도는 타이베이를 대표 지점으로 표시합니다.'}
  ],
  recommendations: [
    {id:'portugal',name:'포르투갈',en:'Portugal',art:'portugal',theme:'city',subtitle:'햇빛이 머무는 골목',description:'리스본의 언덕과 신트라의 궁전에서 만나는 느긋한 유럽.',reason:'파리와 남프랑스가 좋았다면',intro:'도시 산책과 오래된 건축을 좋아한다면 리스본과 신트라를 한 여행으로 묶어보세요. 파리·남프랑스 방문 목록에서 착안한 추천입니다.',spots:['리스본','신트라','카스카이스'],duration:'6–8일 제안',season:'봄·가을 제안',source:'https://www.visitportugal.com/en/destinos/lisboa-regi%C3%A3o/318533',sourceName:'포르투갈 관광청'},
    {id:'slovenia',name:'슬로베니아',en:'Slovenia',art:'lake',theme:'nature',subtitle:'호수 옆의 작은 동화',description:'블레드의 호수와 류블랴나의 여유로운 산책길.',reason:'안시와 스위스가 좋았다면',intro:'호수 풍경과 작은 도시를 함께 즐기고 싶은 여행에 어울립니다. 안시·스위스 방문 목록을 바탕으로 자연과 도시를 연결하는 일정을 제안합니다.',spots:['블레드','류블랴나','보힌'],duration:'5–7일 제안',season:'늦봄·초가을 제안',source:'https://www.slovenia.info/en/places-to-go/regions/ljubljana-central-slovenia',sourceName:'슬로베니아 관광청'},
    {id:'norway',name:'노르웨이',en:'Norway',art:'fjord',theme:'nature',subtitle:'자연 앞에서 잠시 멈춤',description:'베르겐을 시작으로, 피오르가 그려낸 깊고 푸른 풍경.',reason:'스위스의 대자연이 좋았다면',intro:'산과 물이 만드는 장대한 풍경을 좋아한다면 베르겐을 출발점으로 피오르 지역을 살펴보세요. 스위스의 산악 풍경에서 이어지는 여행을 제안합니다.',spots:['베르겐','브뤼겐','플뢰옌산'],duration:'7–10일 제안',season:'여름 제안',source:'https://www.visitnorway.com/places-to-go/fjord-norway/bergen/plan-your-trip/',sourceName:'노르웨이 관광청'},
    {id:'newzealand',name:'뉴질랜드',en:'New Zealand',art:'alps',theme:'nature',subtitle:'아주 멀리, 더 넓은 풍경',description:'남섬의 호수와 산 사이로 이어지는 나만의 로드트립.',reason:'알프스와 호수 여행이 좋았다면',intro:'남섬의 여러 풍경을 이동하며 만나는 여행입니다. 스위스·안시의 산과 호수를 즐겼다면 퀸스타운을 포함한 남섬 일정을 살펴보세요.',spots:['퀸스타운','와나카','남섬'],duration:'10–14일 제안',season:'현지 여름·초가을 제안',source:'https://www.newzealand.com/nz/trips-and-driving-itineraries/south-island/',sourceName:'뉴질랜드 관광청'}
  ]
};
