// Development smoke check. Uses Playwright if installed; not needed to run the site.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173');
 await page.waitForSelector('.travel-card');
 assert.equal(await page.locator('.travel-card').count(),4);
 assert.equal(await page.locator('#map-pins .map-pin').count(),12);
 fs.mkdirSync(path.join(__dirname,'../qa'),{recursive:true});
 await page.evaluate(async()=>{await Promise.all([...document.images].map(img=>{img.loading='eager';return img.decode();}));});
 await page.screenshot({path:path.join(__dirname,'../qa/desktop.png'),fullPage:true});
 await page.locator('#show-more').click();assert.equal(await page.locator('.travel-card').count(),12);
 await page.locator('[data-region="asia"]').click();assert.equal(await page.locator('.travel-card').count(),4);
 await page.locator('#search').fill('일본');assert.equal(await page.locator('.travel-card').count(),1);
 await page.locator('#search').fill('not-a-place');assert.equal(await page.locator('.empty-state').count(),1);
 await page.locator('#reset-search').click();assert.equal(await page.locator('.travel-card').count(),12);
 await page.locator('.card-title[data-detail="london"]').click();
 await page.locator('[name="start"]').fill('2025-04-01');await page.locator('[name="end"]').fill('2025-04-10');await page.locator('[name="text"]').fill('QA 기록 <script>alert(1)</script>');
 await page.locator('#note-form [type="submit"]').click();
 assert.match(await page.locator('.note-status').textContent(),/저장/);
 await page.locator('#detail-dialog .dialog-close').click();
 await page.reload();await page.locator('.card-title[data-detail="london"]').click();assert.equal(await page.locator('[name="text"]').inputValue(),'QA 기록 <script>alert(1)</script>');
 await page.locator('[name="photo"]').setInputFiles(path.join(__dirname,'../assets/hero-landscape.png'));
 await page.locator('#note-form [type="submit"]').click();
 await page.waitForFunction(()=>document.querySelector('.dialog-image').src.startsWith('data:image/jpeg'));
 await page.locator('#detail-dialog .dialog-close').click();
 await page.locator('[data-save="portugal"]').click();assert.equal(await page.locator('#saved-count').textContent(),'1');
 await page.locator('#open-saved').click();assert.equal(await page.locator('.saved-row').count(),1);await page.locator('#saved-dialog .dialog-close').click();
 await page.locator('[data-map="europe"]').click();assert.equal(await page.locator('#map-pins .map-pin').count(),8);
 await page.waitForTimeout(500);
 assert.equal(await page.evaluate(()=>{const r=document.querySelector('#world-map').getBoundingClientRect();return [...document.querySelectorAll('#map-pins .map-pin')].every(p=>{const b=p.getBoundingClientRect();return b.x>=r.x&&b.y>=r.y&&b.right<=r.right&&b.bottom<=r.bottom;});}),true,'European pins must be inside the visible map');
 await page.locator('#atlas').screenshot({path:path.join(__dirname,'../qa/europe.png')});
 await page.locator('#edit-route').click();await page.locator('[data-route-id="london"]').uncheck();await page.locator('[data-index="2"][data-move="-1"]').click();await page.locator('#save-route').click();assert.equal(await page.locator('#route-status').textContent(),'나의 루트');assert.equal(await page.locator('#route-list li').count(),7);
 await page.locator('#add-place').click();await page.locator('#place-form [name="name"]').fill('바르셀로나');await page.locator('#place-form [name="en"]').fill('Barcelona');await page.locator('#place-form [name="country"]').fill('스페인');await page.locator('#place-form [name="description"]').fill('QA 새 여행');await page.locator('#place-form [name="lat"]').fill('41.39');await page.locator('#place-form [name="lon"]').fill('2.17');await page.locator('#place-form [type="submit"]').click();assert.equal(await page.locator('#detail-title').textContent(),'바르셀로나');await page.locator('#detail-dialog .dialog-close').click();assert.equal(await page.locator('#stat-places').textContent(),'13');
 const downloadPromise=page.waitForEvent('download');await page.locator('#export-data').click();const download=await downloadPromise;const backup=path.join(__dirname,'../qa/backup.json');await download.saveAs(backup);
 await page.evaluate(()=>localStorage.clear());await page.reload();assert.equal(await page.locator('#stat-places').textContent(),'12');
 await page.locator('#import-file').setInputFiles(backup);await page.locator('#confirm-import').click();assert.equal(await page.locator('#stat-places').textContent(),'13');assert.equal(await page.locator('#saved-count').textContent(),'1');
 await page.locator('#interest-filter').selectOption('city');assert.equal(await page.locator('.recommend-card').count(),1);
 // Restore a pristine preview, then check direct-file use and a narrow mobile viewport.
 await page.evaluate(()=>localStorage.clear());await page.reload();
 await page.setViewportSize({width:390,height:844});await page.evaluate(async()=>{await Promise.all([...document.images].map(img=>{img.loading='eager';return img.decode();}));});await page.screenshot({path:path.join(__dirname,'../qa/mobile.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('.card-title[data-detail="london"]').click();assert.equal(await page.locator('#detail-dialog').isVisible(),true);await page.keyboard.press('Escape');
 const filePage=await browser.newPage();await filePage.goto('file:///'+path.join(__dirname,'../index.html').replaceAll('\\','/'));await filePage.waitForSelector('.travel-card');assert.equal(await filePage.locator('#map-pins .map-pin').count(),12);await filePage.close();
 assert.deepEqual(errors,[]);
 console.log('PASS: cards, filters, search, notes, reload persistence, photo, wishlist, maps, route, add place, export/import, mobile overflow, keyboard dismissal, direct file loading; no browser errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
